# name: Run Daily Script

# on:
#   schedule:
#     - cron: "0 14 * * *"  # 10:00 AM Puerto Rico (UTC-4)

# jobs:
#   run-script:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.10'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run Python Script
#         env:
#           PG_HOST: ${{ vars.PG_HOST }}
#           PG_USER: ${{ vars.PG_USER }}
#           PG_PASSWORD: ${{ vars.PG_PASSWORD }}
#           PG_DB: ${{ vars.PG_DB }}
#           SQLSERVER_USER: ${{ vars.SQLSERVER_USER }}
#           SQLSERVER_PASSWORD: ${{ vars.SQLSERVER_PASSWORD }}
#           SQLSERVER_SERVER: ${{ vars.SQLSERVER_SERVER }}
#           SQLSERVER_DB: ${{ vars.SQLSERVER_DB }}
#           SQLSERVER_DRIVER: ${{ vars.SQLSERVER_DRIVER }}
#         run: python3 automation/etl/pos/main.py
